services:
  - type: web
    name: hotel-staff
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn hotel_staff.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-staff-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: hotel-staff-db
    plan: free