# Generated by Django 6.0.6 on 2026-06-17 10:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hotel',
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_wage_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Ωρομίσθιος'), ('monthly', 'Μηνιαίος'), ('daily', 'Ημερομίσθιος'), ('none', 'Χωρίς Υπολογισμό')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('is_primary', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_departments', to='staff.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='staff.employee')),
            ],
            options={
                'ordering': ['-is_primary', '-start_date'],
                'unique_together': {('employee', 'department')},
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='employee_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employeedepartment'),
        ),
    ]
