# Generated by Django 6.0.6 on 2026-06-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_globalshifttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHotelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('occupied_rooms', models.PositiveIntegerField(default=0)),
                ('check_ins', models.PositiveIntegerField(default=0)),
                ('check_outs', models.PositiveIntegerField(default=0)),
                ('room_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fb_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extras_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('total_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.hotel')),
            ],
            options={
                'verbose_name': 'Ημερήσια Στατιστικά',
                'verbose_name_plural': 'Ημερήσια Στατιστικά',
                'ordering': ['-date'],
                'unique_together': {('hotel', 'date')},
            },
        ),
    ]
